### ISSUE TITLE
Project still maintained?

### ISSUE THREAD

**Issue by tyrann0us** [e2b/wordpress-hyphenator#4]
Hi @e2b, @odie2,
as the title says, I'd like to know if the project is still maintained. There are lots of support threads on [w.org](https://wordpress.org/support/plugin/hyphenator), most of them unanswered.

Thanks.

**Comment by odie2** [comment]
Hi @tyrann0us 

There was no much time to keep improving it as I initially thought.
I minimalized own use to settings, which was enought for my purposes.

However as fast as I have some time I would need add `filters`. I just wonder I won't have time until May.

If you want help, feel free, then I could handle all updates to official.

Greetings
